# Mettre ici le nom du site (court)
siteName: "Bootstrap Parti Pirate"
# Mettre à true pour la production
is_production: false
# Mettre l'url complète du site de production et finir par un /. ie: https://www.partipirate.org/
url: http://partipirate.github.io/Bootstrap/
# Réseaux sociaux
## compte associé
twitter_account: "@PartiPirate"
facebook_publisher: "https://www.facebook.com/partipiratefr"
## path relatif de l'image par défaut 
twitter_image: "img/twitter_meta.png"
facebook_image: "img/facebook_meta.png"